import { env } from "cloudflare:workers";

type TournamentPayload = { tournament?: unknown };
const schema = `CREATE TABLE IF NOT EXISTS tournaments (id TEXT PRIMARY KEY NOT NULL, edit_token_hash TEXT NOT NULL, data TEXT NOT NULL, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`;

async function hash(value: string) { const bytes = new TextEncoder().encode(value); const digest = await crypto.subtle.digest("SHA-256", bytes); return [...new Uint8Array(digest)].map((b) => b.toString(16).padStart(2, "0")).join(""); }
async function ensureTable() { await env.DB.prepare(schema).run(); }
function validTournament(value: unknown) { if (!value || typeof value !== "object") return false; const t = value as { name?: unknown; players?: unknown; matches?: unknown }; return typeof t.name === "string" && Array.isArray(t.players) && Array.isArray(t.matches); }

export async function GET(request: Request) { await ensureTable(); const id = new URL(request.url).searchParams.get("id"); if (!id) return Response.json({ error: "Missing tournament id" }, { status: 400 }); const row = await env.DB.prepare("SELECT data, updated_at FROM tournaments WHERE id = ?").bind(id).first<{ data: string; updated_at: string }>(); if (!row) return Response.json({ error: "Tournament not found" }, { status: 404 }); return Response.json({ tournament: JSON.parse(row.data), updatedAt: row.updated_at }, { headers: { "cache-control": "no-store" } }); }
export async function POST(request: Request) { await ensureTable(); const body = await request.json() as TournamentPayload; if (!validTournament(body.tournament)) return Response.json({ error: "Invalid tournament" }, { status: 400 }); const data = JSON.stringify(body.tournament); if (data.length > 200000) return Response.json({ error: "Tournament is too large" }, { status: 413 }); const id = crypto.randomUUID().replaceAll("-", "").slice(0, 10); const editToken = crypto.randomUUID() + crypto.randomUUID(); await env.DB.prepare("INSERT INTO tournaments (id, edit_token_hash, data) VALUES (?, ?, ?)").bind(id, await hash(editToken), data).run(); return Response.json({ id, editToken }, { status: 201 }); }
export async function PUT(request: Request) { await ensureTable(); const id = new URL(request.url).searchParams.get("id"); const token = request.headers.get("x-edit-token") || ""; if (!id || !token) return Response.json({ error: "Not authorized" }, { status: 401 }); const stored = await env.DB.prepare("SELECT edit_token_hash FROM tournaments WHERE id = ?").bind(id).first<{ edit_token_hash: string }>(); if (!stored || stored.edit_token_hash !== await hash(token)) return Response.json({ error: "Not authorized" }, { status: 403 }); const body = await request.json() as TournamentPayload; if (!validTournament(body.tournament)) return Response.json({ error: "Invalid tournament" }, { status: 400 }); const data = JSON.stringify(body.tournament); if (data.length > 200000) return Response.json({ error: "Tournament is too large" }, { status: 413 }); await env.DB.prepare("UPDATE tournaments SET data = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?").bind(data, id).run(); return Response.json({ ok: true }); }
